// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// inner_integral_vec_rcpp
NumericVector inner_integral_vec_rcpp(NumericVector& x, NumericVector& a, double b);
RcppExport SEXP _PEStimate_inner_integral_vec_rcpp(SEXP xSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(inner_integral_vec_rcpp(x, a, b));
    return rcpp_result_gen;
END_RCPP
}
// selected_score_rcpp
NumericVector selected_score_rcpp(NumericMatrix embryo_scores, int iter, double prs_threshold);
RcppExport SEXP _PEStimate_selected_score_rcpp(SEXP embryo_scoresSEXP, SEXP iterSEXP, SEXP prs_thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type embryo_scores(embryo_scoresSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< double >::type prs_threshold(prs_thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(selected_score_rcpp(embryo_scores, iter, prs_threshold));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PEStimate_inner_integral_vec_rcpp", (DL_FUNC) &_PEStimate_inner_integral_vec_rcpp, 3},
    {"_PEStimate_selected_score_rcpp", (DL_FUNC) &_PEStimate_selected_score_rcpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_PEStimate(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
