# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
inner_integral_vec_rcpp <- function(x, a, b) {
    .Call('_PEStimate_inner_integral_vec_rcpp', PACKAGE = 'PEStimate', x, a, b)
}

#' @export
selected_score_rcpp <- function(embryo_scores, iter, prs_threshold) {
    .Call('_PEStimate_selected_score_rcpp', PACKAGE = 'PEStimate', embryo_scores, iter, prs_threshold)
}

